/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import ahorcado.manejadorAhorcado;
import java.awt.List;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jonyasus
 */
public class game6 extends javax.swing.JFrame {

    static ArrayList<String> letrasUsadas;
    static ArrayList<String> letrasDePalabra;
    static ArrayList<String> letrasEnPantalla;
    static ArrayList<String> pistas;
    int cantidadVidas = 7;
    int cantidadPistasUsadas = 0;

    /**
     * Creates new form game6
     */
    public game6() {
        letrasUsadas = new ArrayList<>();
        letrasDePalabra = new ArrayList<>();
        letrasEnPantalla = new ArrayList<>();
        pistas = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        letraIngresada = new javax.swing.JTextField();
        vidasDisponibles = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        letrasUsadasTextArea = new javax.swing.JTextArea();
        verPista = new javax.swing.JButton();
        intentar = new javax.swing.JButton();
        palabraSecreta = new javax.swing.JTextField();
        pista1TextField = new javax.swing.JTextField();
        pista2Texfield = new javax.swing.JTextField();
        pista3Textfield = new javax.swing.JTextField();
        procesoPalabra = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        newGame = new javax.swing.JMenu();
        nuevoJuego = new javax.swing.JMenuItem();
        salirButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ahorcado");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estado");

        jLabel2.setText("La palabra es:");

        jLabel3.setText("Elección:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel4.setText("(Ingresa una letra)");

        jLabel5.setText("Vidas:");

        jLabel6.setText("Letras usadas:");

        letraIngresada.setEditable(false);
        letraIngresada.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        letraIngresada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letraIngresada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraIngresadaActionPerformed(evt);
            }
        });
        letraIngresada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letraIngresadaKeyTyped(evt);
            }
        });

        vidasDisponibles.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        letrasUsadasTextArea.setEditable(false);
        letrasUsadasTextArea.setColumns(20);
        letrasUsadasTextArea.setRows(5);
        jScrollPane2.setViewportView(letrasUsadasTextArea);

        verPista.setText("Ver Pista");
        verPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPistaActionPerformed(evt);
            }
        });

        intentar.setText("¡Probar!");
        intentar.setEnabled(false);
        intentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intentarActionPerformed(evt);
            }
        });

        palabraSecreta.setText("jTextField1");

        pista1TextField.setText("jTextField2");

        pista2Texfield.setText("jTextField3");

        pista3Textfield.setText("jTextField4");

        procesoPalabra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        newGame.setText("Opciones");
        newGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameMouseClicked(evt);
            }
        });
        newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });

        nuevoJuego.setText("Nuevo juego");
        nuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoJuegoActionPerformed(evt);
            }
        });
        newGame.add(nuevoJuego);

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        newGame.add(salirButton);

        jMenuBar1.add(newGame);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(intentar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(letraIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(palabraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(pista1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pista2Texfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pista3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(verPista)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(38, 38, 38)
                                    .addComponent(vidasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(procesoPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palabraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pista1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pista2Texfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pista3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(procesoPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(letraIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intentar)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vidasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(verPista)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPistaActionPerformed
        if (cantidadPistasUsadas < 3) {
            JOptionPane.showMessageDialog(null, "PISTA: " + pistas.get(cantidadPistasUsadas));
            cantidadPistasUsadas++;
            cantidadVidas--;
            String vidas = String.valueOf(cantidadVidas);
            vidasDisponibles.setText(vidas);
        } else {
            JOptionPane.showMessageDialog(null, "¡Te has quedado sin pistas!");
        }

    }//GEN-LAST:event_verPistaActionPerformed

    private void letraIngresadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraIngresadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letraIngresadaActionPerformed

    private void letraIngresadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letraIngresadaKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && car != 'ñ') {
            evt.consume();
        }
        keyTyped(evt);
    }//GEN-LAST:event_letraIngresadaKeyTyped

    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameActionPerformed

    }//GEN-LAST:event_newGameActionPerformed

    private void newGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameMouseClicked

    }//GEN-LAST:event_newGameMouseClicked

    private void nuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoJuegoActionPerformed
        newGame();
    }//GEN-LAST:event_nuevoJuegoActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_salirButtonActionPerformed

    private void intentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intentarActionPerformed
        String letrasUtilizadas = "";
        if (verificarLetraUsada(letraIngresada.getText()) == false) {

            if (letraExisteEnPalabra(letraIngresada.getText()) && cantidadVidas > 1) {
                letrasUsadas.add(letraIngresada.getText());
                JOptionPane.showMessageDialog(null, "¡Haz acertado!");
                indexLetraACambiar(letraIngresada.getText());
                mostrarPalabra();
            } else {
                letrasUsadas.add(letraIngresada.getText());
                JOptionPane.showMessageDialog(null, "¡Haz fallado!");
                cantidadVidas--;
            }

        } else {
            JOptionPane.showMessageDialog(null, "¡Ya ingresaste esa letra!");

        }

        letraIngresada.setText("");
        mostrarLetrasUsadas();
        String vidas = String.valueOf(cantidadVidas);
        vidasDisponibles.setText(vidas);
        procesoPalabra.setText("");
        procesoPalabra.setText(mostrarPalabra());
        for (int i = 0; i < letrasUsadas.size(); i++) {
            letrasUtilizadas += " " + letrasUsadas.get(i);
        }
        letrasUsadasTextArea.setText(letrasUtilizadas);

        if (cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "¡Has sido ahorcado!");
            resetear();
            bloquearTodo();
            
        }
    }//GEN-LAST:event_intentarActionPerformed

    public void keyTyped(KeyEvent e) {
        if (letraIngresada.getText().length() == 1) {
            e.consume();
        }
    }

    private void newGame() {
        //JOptionPane.showInputDialog(this);
        String vidas = String.valueOf(cantidadVidas);
        vidasDisponibles.setText(vidas);
        String palabraNueva = palabraSecreta.getText();
        String pista1 = pista1TextField.getText();
        String pista2 = pista2Texfield.getText();
        String pista3 = pista3Textfield.getText();
        agregarPista(pista1);
        agregarPista(pista2);
        agregarPista(pista3);
        for (int i = 0; i < palabraNueva.length(); i++) {
            char letra = palabraNueva.charAt(i);
            String s = String.valueOf(letra);
            letrasDePalabra.add(s);
            System.out.println(letrasDePalabra.get(i));
        }
        for (int i = 0; i < palabraNueva.length(); i++) {
            letrasEnPantalla.add(" __");
        }

        procesoPalabra.setText(mostrarPalabra());
        habilitarTodo();
        vidasDisponibles.setText(Integer.toString(cantidadVidas));
    }

    private void bloquearTodo() {
        letraIngresada.setEditable(false);
        verPista.setEnabled(false);
        intentar.setEnabled(false);
    }

    private void habilitarTodo() {
        letraIngresada.setEditable(true);
        verPista.setEnabled(true);
        intentar.setEnabled(true);
    }

    public void obtenerPalabraPorLetras(String textoEntrada) {
        for (int i = 0; i < textoEntrada.length(); i++) {
            char letra = textoEntrada.charAt(i);
            String s = String.valueOf(letra);
            letrasDePalabra.add(s);
        }
    }

    public boolean letraExisteEnPalabra(String letra) {
        for (int i = 0; i < letrasDePalabra.size(); i++) {
            if (letra.equalsIgnoreCase(letrasDePalabra.get(i))) {
                return true;
            } else {
            }
        }
        return false;
    }

    public void crearPalabra() {
        for (int i = 0; i < letrasDePalabra.size(); i++) {
            letrasEnPantalla.add("__ ");
        }
    }

    public String mostrarPalabra() {
        String letraString = "";
        for (int i = 0; i < letrasEnPantalla.size(); i++) {
            letraString += String.valueOf(letrasEnPantalla.get(i));
        }
        return letraString;
    }

    public void indexLetraACambiar(String letra) {
        for (int i = 0; i < letrasDePalabra.size(); i++) {
            if (letra.equalsIgnoreCase(letrasDePalabra.get(i))) {
                letrasEnPantalla.set(i, letra);
            }
        }
    }

    public void mostrarPista() {
        int numPista = cantidadPistasUsadas + 1;
        JOptionPane.showMessageDialog(null, "Pista #" + numPista + ": " + pistas.get(cantidadPistasUsadas));
        cantidadPistasUsadas++;
    }

    public void mostrarLetrasUsadas() {
        for (int i = 0; i < letrasUsadas.size(); i++) {
            System.out.println("Usada: " + letrasUsadas.get(i));
        }
    }

    public void agregarPista(String pista) {
        pistas.add(pista);
    }

    public boolean verificarLetraUsada(String letra) {
        for (int i = 0; i < letrasUsadas.size(); i++) {
            if (letra.equalsIgnoreCase(letrasUsadas.get(i))) {
                return true;
            }
        }
        return false;
    }
    
    public void resetear(){
    letrasDePalabra.clear();
    letrasEnPantalla.clear();
    letrasUsadas.clear();
    cantidadVidas=7;
    palabraSecreta.setText("");
    pista1TextField.setText("");
    pista2Texfield.setText("");
    pista3Textfield.setText("");
    letrasUsadasTextArea.setText("");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton intentar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField letraIngresada;
    private javax.swing.JTextArea letrasUsadasTextArea;
    private javax.swing.JMenu newGame;
    private javax.swing.JMenuItem nuevoJuego;
    private javax.swing.JTextField palabraSecreta;
    private javax.swing.JTextField pista1TextField;
    private javax.swing.JTextField pista2Texfield;
    private javax.swing.JTextField pista3Textfield;
    private javax.swing.JLabel procesoPalabra;
    private javax.swing.JMenuItem salirButton;
    private javax.swing.JButton verPista;
    private javax.swing.JLabel vidasDisponibles;
    // End of variables declaration//GEN-END:variables
}
